aws:
  region: af-south-1
  bucket: cct-ds-code-challenge-input-data

sources:
  service_requests:
    key: sr.csv.gz
    format: csv
    compression: gzip

  service_requests_hex:
    key: sr_hex.csv.gz
    format: csv
    compression: gzip

  service_requests_hex_truncated:
    key: sr_hex_truncated.csv
    format: csv

  hex_polygons_8:
    key: city-hex-polygons-8.geojson
    format: geojson

  hex_polygons_8_10:
    key: city-hex-polygons-8-10.geojson
    format: geojson